### ISSUE TITLE
transformObjectKeys - duplicate variable declaration

### ISSUE THREAD

**Issue by beeing** [javascript-obfuscator/javascript-obfuscator#550]
Hi, managed to reproduce the error with a minimal example below:

Error will only happen if exceeds 50 assignments.

```js
const a1 = { x: 1 }
, a2 = { x: 2 }
, a3 = { x: 3 }
, a4 = { x: 4 }
, a5 = { x: 5 }
, a6 = { x: 6 }
, a7 = { x: 7 }
, a8 = { x: 8 }
, a9 = { x: 9 }
, a10 = { x: 10 }
, a11 = { x: 11 }
, a12 = { x: 12 }
, a13 = { x: 13 }
, a14 = { x: 14 }
, a15 = { x: 15 }
, a16 = { x: 16 }
, a17 = { x: 17 }
, a18 = { x: 18 }
, a19 = { x: 19 }
, a20 = { x: 20 }
, a21 = { x: 21 }
, a22 = { x: 22 }
, a23 = { x: 23 }
, a24 = { x: 24 }
, a25 = { x: 25 }
, a26 = { x: 26 }
, a27 = { x: 27 }
, a28 = { x: 28 }
, a29 = { x: 29 }
, a30 = { x: 30 }
, a31 = { x: 31 }
, a32 = { x: 32 }
, a33 = { x: 33 }
, a34 = { x: 34 }
, a35 = { x: 35 }
, a36 = { x: 36 }
, a37 = { x: 37 }
, a38 = { x: 38 }
, a39 = { x: 39 }
, a40 = { x: 40 }
, a41 = { x: 41 }
, a42 = { x: 42 }
, a43 = { x: 43 }
, a44 = { x: 44 }
, a45 = { x: 45 }
, a46 = { x: 46 }
, a47 = { x: 47 }
, a48 = { x: 48 }
, a49 = { x: 49 }
, a50 = { x: 50 }
, a51 = { x: 51 }
```

**Comment by sanex3339** [comment]
The problem can be easily reproduced just with this code:
```
const c = { x: 1 };
```

and 
```
transformObjectKeys: true
```

**Comment by beeing** [comment]
Yes, that's the shortest test.

Should add this into the unit tests too.

**Comment by sanex3339** [comment]
Can you try this branch?
https://github.com/javascript-obfuscator/javascript-obfuscator/pull/552

Will it help?

**Comment by beeing** [comment]
Tested and looks good - no more duplicate variable errors.

**Comment by sanex3339** [comment]
Can you also test it on?
#555

**Comment by beeing** [comment]
Did a quick test, hit errors below in different files:

- ReferenceError: Cannot access 'cO' before initialization
- Identifier 'bf' has already been declared

Can narrow down the cause if needed.

**Comment by sanex3339** [comment]
It would be great

**Comment by beeing** [comment]
Is there anyway to create a branch version of the obfuscator.io web obfuscate and evaluate?

This will help to speed up finding the problem.

**Comment by sanex3339** [comment]
you can just clone this repo
https://github.com/javascript-obfuscator/javascript-obfuscator-ui

**Comment by sanex3339** [comment]
Try to disable self defending, domain lock, debug protection. Error still happens?

**Comment by sanex3339** [comment]
Updated PR. Please try now #555.

**Comment by beeing** [comment]
Self defending, domain lock, debug protection is disabled when I tested this.

**Comment by beeing** [comment]
Oh, to be clear, comment in https://github.com/javascript-obfuscator/javascript-obfuscator/issues/550#issuecomment-585213719 is referring to the `variable-preserve-improvements` branch.

And I just tested `new-mangled-names-generator` the error is:

- Identifier 'b' has already been declared

**Comment by beeing** [comment]
The `new-mangled-names-generator` branch have same bug as https://github.com/javascript-obfuscator/javascript-obfuscator/issues/550#issuecomment-583743033

**Comment by sanex3339** [comment]
Hmm. Cant reproduce 
https://github.com/javascript-obfuscator/javascript-obfuscator/issues/550#issue-561958467
and
https://github.com/javascript-obfuscator/javascript-obfuscator/issues/550#issuecomment-583743033

**Comment by beeing** [comment]
So which branch to test on? Then I'll check it out when I'm free.

**Comment by sanex3339** [comment]
`new-mangled-names-generator`. This branch contains all changes from `variable-preserve-improvements` and also I re-implemented much smarter `idenitiferNamesGenerator: 'mangled'`.

So, with new `idenitiferNamesGenerator: 'mangled'` implementation I got few `Identifier 'b' has already been declared` errors, related to the `debugProtection, selfDefending and domainLock` options. But I fixed it with the last commit, and after that, I asked you to test this branch.

So, it looks like there is something else, that I did not catch.

**Comment by beeing** [comment]
I tried pulling the branch (into my node_modules replacing the javascript-obfuscator directory) and re-run it but still getting result as above.

**Comment by sanex3339** [comment]
Can you show your options, and code if possible?

**Comment by beeing** [comment]
Options as below:

```js
    target: 'node',
    identifierNamesGenerator: 'mangled',
    rotateStringArray: true,
    splitStrings: true,
    splitStringsChunkLength: 15,
    stringArray: true,
    stringArrayEncoding: 'base64',
    stringArrayThreshold: 0.9,
    shuffleStringArray: true,
    transformObjectKeys: true,
```

The rest is false. For code, I will need to prepare first.

**Comment by sanex3339** [comment]
Merged `new-mangled-names-generator` to the `variable-preserve-improvements` branch. Now all tests should be on `variable-preserve-improvements`

**Comment by beeing** [comment]
Testing on latest `variable-preserve-improvements` branch, it seems that it goes into infinite loop.

**Comment by sanex3339** [comment]
Please, provide options each time when something wrong, because i have no idea what is wrong without options and details.

**Comment by sanex3339** [comment]
I fixed another problem. You can try again. Not sure if it helps btw.

**Comment by sanex3339** [comment]
My tests are passed. So, if you still have any problems, i need to know how to reproduce it, because without it i can't write regression tests and fix it.

**Comment by beeing** [comment]
Hi @sanex3339, the options I used is the same as https://github.com/javascript-obfuscator/javascript-obfuscator/issues/550#issuecomment-585602790.

Just tested the latest also going to an infinite loop.

One note, I can't find which file is causing this because the CLI output will list all the files like: `[javascript-obfuscator-cli] Obfuscating file: ...` upfront rather than showing the file name when it starts to process on that file.

**Comment by sanex3339** [comment]
You can try again.
I spent a whole day to fix many bugs. Changed a huge amount of things.
I added more runtime tests: webpack bootstrap code, and now in tests, I obfuscate obfuscator itself.
These tests allowed me to find and fix many bugs.
Also, I had to rework the self-defending code, so now it slightly smaller. And when the self-defending mechanism will be triggered, it will freeze the browser without the `maximum call stack` error.

**Comment by beeing** [comment]
Appreciated your time spent. However, it is still the same. I turned on the log but there's no filename in the log.

The only info I found is it stuck at Preparing... stage.

Will be helpful if the filename is included in the log.

Hope this helps.

```
[A lot more logs above...]

[javascript-obfuscator] Version: 0.25.0

[javascript-obfuscator] Obfuscation started...

[javascript-obfuscator] Random generator seed: 344031425...

[javascript-obfuscator] Transformation stage: Initializing...

[javascript-obfuscator] Transformation stage: Preparing...

[javascript-obfuscator] Transformation stage: Converting...

[javascript-obfuscator] Transformation stage: Obfuscating...

[javascript-obfuscator] Transformation stage: Finalizing...

[javascript-obfuscator] Obfuscation completed. Total time: 1.797 sec.

[javascript-obfuscator] Version: 0.25.0

[javascript-obfuscator] Obfuscation started...

[javascript-obfuscator] Random generator seed: 156613164...

[javascript-obfuscator] Transformation stage: Initializing...

[javascript-obfuscator] Transformation stage: Preparing...

[javascript-obfuscator] Transformation stage: Converting...

[javascript-obfuscator] Transformation stage: Obfuscating...

[javascript-obfuscator] Transformation stage: Finalizing...

[javascript-obfuscator] Obfuscation completed. Total time: 0.031 sec.

[javascript-obfuscator] Version: 0.25.0

[javascript-obfuscator] Obfuscation started...

[javascript-obfuscator] Random generator seed: 127309717...

[javascript-obfuscator] Transformation stage: Initializing...

[javascript-obfuscator] Transformation stage: Preparing...
```

**Comment by sanex3339** [comment]
So, it stucked during obfuscation? Not during code evaluation?

**Comment by sanex3339** [comment]
> Testing on latest `variable-preserve-improvements` branch, it seems that it goes into infinite loop.

I'mabout this comment

**Comment by sanex3339** [comment]
I added build time to the version message.
Could you update from this branch again and show me log messages with the version?
I want to be sure that you're using the latest build.

**Comment by beeing** [comment]
Sorry for not being clear enough, yes it stuck during obfuscation.

Below is the latest log and stuck in the Preparing...

```
[javascript-obfuscator] Version: 0.25.0_2020-02-16T21:43:37.017Z

[javascript-obfuscator] Obfuscation started...

[javascript-obfuscator] Random generator seed: 410740464...

[javascript-obfuscator] Transformation stage: Initializing...

[javascript-obfuscator] Transformation stage: Preparing...
```

**Comment by sanex3339** [comment]
Hi. Any news about the possibility of providing your code for me to debug?

**Comment by beeing** [comment]
I will send you by email. Also for the infinite loop, I'm still waiting for the log that includes the filename that is being processed.

So, I can narrow down the exact file that cause this problem.

**Comment by sanex3339** [comment]
About the filename, how did you use obfuscator? Via CLI, node API or webpack plugin?
Currently, filenames should works only via CLI

**Comment by sanex3339** [comment]
Will add file name to the log

**Comment by sanex3339** [comment]
How did you obfuscate your code? Via CLI, node.js API or plugin?

Because currently via CLI you should have an output like:
```
[javascript-obfuscator-cli] Obfuscating file: test/a.js... 

[javascript-obfuscator-cli] Obfuscating file: test/b.js... 
```

**Comment by beeing** [comment]
I'm using CLI with command as below:

```
javascript-obfuscator dist --config ./config.js --exclude node_modules --output obfuscated
```

**Comment by sanex3339** [comment]
Cannot reproduce.

For me it shows file paths:

```
[javascript-obfuscator-cli] Obfuscating file: dist/a.js... 

[javascript-obfuscator-cli] Obfuscating file: dist/b.js... 
```

**Comment by sanex3339** [comment]
So, the problem here
https://github.com/javascript-obfuscator/javascript-obfuscator/blob/master/src/cli/utils/SourceCodeReader.ts#L116

But i have no idea why did you get an empty path here.

**Comment by beeing** [comment]
Ok, not sure this helps. The log is set to true in the config and when run in CLI, the log appears as below...

```
[javascript-obfuscator-cli] Obfuscating file: dist/some-file.js...

[javascript-obfuscator-cli] Obfuscating file: dist/last-file.js...

[javascript-obfuscator] Version: 0.25.0_2020-02-16T21:43:37.017Z

[javascript-obfuscator] Obfuscation started...

[javascript-obfuscator] Random generator seed: 595688770...

[javascript-obfuscator] Transformation stage: Initializing...

[javascript-obfuscator] Transformation stage: Preparing...
```

I noticed that there is two prefix `[javascript-obfuscator-cli]` and `[javascript-obfuscator]` which the latter does not have filename.

I believe we need to have filename added here: https://github.com/javascript-obfuscator/javascript-obfuscator/blob/f450b63eb840c2ec9859916d70e11a725a8c26a6/src/JavaScriptObfuscator.ts#L128

Will need to pass in the inputOptions from the Facade when calling `obfuscate(sourceCode)` so it can include inputFilePath in the log.

**Comment by sanex3339** [comment]
No. The main app shouldn't know about the file name.
I will output the file name only on the CLI side

**Comment by sanex3339** [comment]
The problem is that it shows all `Obfuscating file` messages at first and only after that - log messages of the obfuscation stages

**Comment by sanex3339** [comment]
I will fix it in a few hours

**Comment by sanex3339** [comment]
I updated it. Now the file names should display in the correct places

**Comment by sanex3339** [comment]
Hi. Any news? This is the only reason why I still didn't merge this PR to the `master` branch

**Comment by beeing** [comment]
Yes, just emailed to you.

**Comment by sanex3339** [comment]
I didn't get anything on my primary mail `sanex3339 a t yandex` and `javascript-obfuscator a t yandex`

**Comment by sanex3339** [comment]
Found the problem with `Identifier 'a' has already been declared`.
Will try to fix it

**Comment by sanex3339** [comment]
But what about infinity loop?

**Comment by sanex3339** [comment]
Updated. Try now.

**Comment by beeing** [comment]
Latest test looks good. Test based on https://github.com/javascript-obfuscator/javascript-obfuscator/issues/550#issuecomment-585602790

No more errors and infinite loop. Thanks.

**Comment by sanex3339** [comment]
Finally! Thank you for the help!
I think i will release `beta` version later today or tomorrow

**Comment by sanex3339** [comment]
Actually why not? Released as `0.25.0` just a few seconds ago. Thank you again for your help!

**Comment by beeing** [comment]
Hi, apparently this will cause `c[a139b(...)] is not a function` error if I disable `transformObjectKeys`.

**Comment by sanex3339** [comment]
Can you send a file?

**Comment by beeing** [comment]
You can use the same file.

**Comment by sanex3339** [comment]
Will try. Options as described above, but without transform object keys?

**Comment by beeing** [comment]
Yes.

**Comment by sanex3339** [comment]
Hi. Tried a few times with options:
```
module.exports = {
    compact: false,
    target: 'node',
    identifierNamesGenerator: 'mangled',
    rotateStringArray: true,
    splitStrings: true,
    splitStringsChunkLength: 15,
    stringArray: true,
    stringArrayEncoding: 'base64',
    stringArrayThreshold: 0.9,
    shuffleStringArray: true
};
```

I commented this lines:
```
/*const extend = require("extend");
const primitives_1 = require("lib/primitives");
const utils_1 = require("lib/utils");
const part_1 = require("lib/sql/part");
const util_1 = require("util");*/
```

And just tried to evaluate code with node.js:
```
node index-obfuscated.js --config coonfig.js
```

No errors for me

**Comment by sanex3339** [comment]
Code to reproduce:
```
function foo() {
  var foo = 1;

  return () => {
  	const { a } = {a: 3};
    
    console.log(foo, a);
  };
}
foo();
```

**Comment by sanex3339** [comment]
The fix here:
https://github.com/javascript-obfuscator/javascript-obfuscator/pull/562

**Comment by beeing** [comment]
Tested and it works. Thanks.

**Comment by sanex3339** [comment]
Released as `0.25.1`
